# Nombre del flujo de trabajo visible en la interfaz de GitHub Actions
name: CI/CD Pipeline

# Evento que dispara el flujo de trabajo: cada vez que se hace un 'push' al branch 'main'
on:
  push:
    branches:
      - main

# Define los trabajos (jobs) que se ejecutar\u00e1n en este flujo de trabajo
jobs:
  # Nombre del primer trabajo: 'build-and-deploy'
  build-and-deploy:
    # El trabajo se ejecutar\u00e1 en la \u00faltima versi\u00f3n de Ubuntu disponible
    runs-on: ubuntu-latest

    # Define los pasos (steps) que conforman el trabajo
    steps:
      # Paso 1: Checkout del repositorio
      # Descarga el c\u00f3digo del repositorio en el que se ejecuta el flujo de trabajo
      - name: Checkout repository
        uses: actions/checkout@v2

      # Paso 2: Configurar Node.js
      # Instala una versi\u00f3n espec\u00edfica de Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      # Paso 3: Instalar dependencias
      - name: Install dependencies
        run: npm install

      # Paso 4: Ejecutar las pruebas unitarias
      - name: Run unit tests
        run: npm test

      # Paso 5: Autenticarse en Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Paso 6: Construir y subir la imagen de Docker
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/practica-final-devops:latest

      # Paso 7: Desplegar en Render
      - name: Deploy to Render
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}